import * as Engine from './engine-client.mjs';
import { guides, keyboardRows } from './content.mjs';
import { validateCollection, searchWords } from './word-lookup.mjs';

const $ = (id) => document.getElementById(id);
const STORAGE_KEY = 'alyas-nasiri.workspace.v1';
const MAX_DOCS = Engine.MAX_DOCUMENTS || 30;
const MAX_BYTES = Engine.MAX_TEXT_BYTES || 1_000_000;
let workspace = { version: 1, activeId: null, documents: [] };
let history = [];
let saveTimer = 0;
let keyboard = null;
let specialLetters = [];
let searchState = [];
let latestPacket = null;
let currentParse = null;
let labTab = 'structure';
let savedSelection = { start: 0, end: 0 };
let practiceChars = [];
let practiceIndex = 0;
let labTextBacking = '';
let corruptWorkspaceBackup = null;
let externalConflictHold = false;
let currentRoute = 'word';
let wordCollection = null;
let wordTimer = 0;
let wordSelection = { start: 0, end: 0 };
let wordCollectionLabel = '';
let wordHashError = false;

function now() { return new Date().toISOString(); }
function id() { return `doc-${Date.now()}-${Math.random().toString(16).slice(2)}`; }
function bytes(text) { return new TextEncoder().encode(text).byteLength; }
function scalarCount(text) { return Array.from(text).length; }
function displayToBacking(text, offset) { let source = 0, shown = 0; while (source < text.length && shown < offset) { if (text[source] === '\r' && text[source + 1] === '\n') { source += 2; shown += 1; } else { source += 1; shown += 1; } } return source; }
function backingToDisplay(text, offset) { let source = 0, shown = 0; while (source < text.length && source < offset) { if (text[source] === '\r' && text[source + 1] === '\n') { source += 2; shown += 1; } else { source += 1; shown += 1; } } return shown; }
function active() { return workspace.documents.find(d => d.id === workspace.activeId) || null; }
function titleFor(d) { return d.title.trim() || 'Untitled document'; }
function toast(message) { const el = $('toast'); el.textContent = message; el.classList.add('show'); clearTimeout(el._timer); el._timer = setTimeout(() => el.classList.remove('show'), 2600); }
function setSave(message) { $('save-status').textContent = message; }
function safeName(value, fallback = 'document') { return (value || fallback).replace(/[\\/:*?"<>|\u0000-\u001f]/g, '-').trim().slice(0, 90) || fallback; }
function clear(node) { while (node.firstChild) node.removeChild(node.firstChild); }
function el(tag, attrs = {}, children = []) { const node = document.createElement(tag); for (const [key, value] of Object.entries(attrs)) { if (value === null || value === undefined || value === false) continue; if (key === 'class') node.className = value; else if (key === 'text') node.textContent = value; else if (key.startsWith('on')) node.addEventListener(key.slice(2), value); else if (value === true) node.setAttribute(key, ''); else node.setAttribute(key, value); } for (const child of children) node.append(child); return node; }
function recoveryKey() { return `${STORAGE_KEY}.recovery`; }
function readRecoveryBundle() { try { const stored = localStorage.getItem(recoveryKey()); if (!stored) return { version: 1, recoveries: [] }; const parsed = JSON.parse(stored); if (parsed?.version === 1 && Array.isArray(parsed.recoveries)) return parsed; return { version: 1, recoveries: [{ capturedAt: now(), reason: 'legacy recovery', data: stored }] }; } catch { return { version: 1, recoveries: [] }; } }
function hasRecovery() { return readRecoveryBundle().recoveries.length > 0; }
function retainRecovery(raw, reason) { if (typeof raw !== 'string' || !raw) return false; try { const bundle = readRecoveryBundle(); bundle.recoveries.push({ capturedAt: now(), reason, data: raw }); bundle.recoveries = bundle.recoveries.slice(-6); localStorage.setItem(recoveryKey(), JSON.stringify(bundle)); return true; } catch { return false; } }

function newDocument(title = '', text = '') { return { id: id(), title, text, createdAt: now(), updatedAt: now(), archived: false, direction: 'auto', font: 'naskh', originalText: text }; }
function emptyWorkspace() { const d = newDocument(); workspace = { version: 1, activeId: d.id, documents: [d] }; }
function validateWorkspace(value) {
  if (!value || value.version !== 1 || !Array.isArray(value.documents) || value.documents.length < 1 || value.documents.length > MAX_DOCS) throw new Error('This workspace file does not have a supported document list.');
  const seen = new Set();
  const docs = value.documents.map((d) => {
    if (!d || typeof d.id !== 'string' || !d.id || seen.has(d.id) || typeof d.title !== 'string' || typeof d.text !== 'string') throw new Error('This workspace file contains an invalid document.');
    seen.add(d.id); Engine.validateText(d.text); if (typeof d.originalText === 'string') Engine.validateText(d.originalText); if (bytes(d.text) > MAX_BYTES) throw new Error(`“${d.title || 'Untitled document'}” is larger than the text limit.`);
    return { id: d.id, title: d.title.slice(0, 120), text: d.text, createdAt: typeof d.createdAt === 'string' ? d.createdAt : now(), updatedAt: typeof d.updatedAt === 'string' ? d.updatedAt : now(), archived: Boolean(d.archived), direction: ['auto','rtl','ltr'].includes(d.direction) ? d.direction : 'auto', font: ['system','naskh','nastaliq'].includes(d.font) ? d.font : 'system', originalText: typeof d.originalText === 'string' ? d.originalText : d.text };
  });
  if (!docs.some(d => !d.archived)) throw new Error('This workspace has no active documents to open.');
  return { version: 1, activeId: docs.some(d => d.id === value.activeId && !d.archived) ? value.activeId : docs.find(d => !d.archived).id, documents: docs };
}
function saveWorkspace() {
  try { if (externalConflictHold) { setSave('Save paused after another tab changed this workspace'); return false; } if (corruptWorkspaceBackup !== null) { if (!retainRecovery(corruptWorkspaceBackup, 'unreadable local workspace')) { setSave('Recovery copy could not be stored'); $('download-recovery').hidden = false; return false; } corruptWorkspaceBackup = null; } localStorage.setItem(STORAGE_KEY, JSON.stringify(workspace)); setSave('Saved locally'); return true; }
  catch (error) { setSave('Could not save locally'); toast('The browser could not save this change. Export a workspace copy.'); return false; }
}
function loadWorkspace() { let saved = null; try { saved = localStorage.getItem(STORAGE_KEY); if (saved) workspace = validateWorkspace(JSON.parse(saved)); else emptyWorkspace(); } catch { corruptWorkspaceBackup = saved; emptyWorkspace(); setSave('Local workspace needs recovery'); } }
function flushSave() { if (saveTimer) { clearTimeout(saveTimer); saveTimer = 0; saveWorkspace(); } }
function saveSoon() { clearTimeout(saveTimer); setSave('Saving…'); saveTimer = setTimeout(() => { saveTimer = 0; saveWorkspace(); }, 450); }
function renderDocuments(showArchived = false) { const list = $('document-list'); clear(list); const docs = workspace.documents.filter(d => showArchived ? d.archived : !d.archived); if (!docs.length) list.append(el('p', { class: 'empty-note', text: showArchived ? 'No archived documents.' : 'No active documents.' })); for (const d of docs) { const button = el('button', { type: 'button', class: `doc-row ${d.id === workspace.activeId ? 'active' : ''}`, 'data-document-id': d.id }, [el('strong', { text: titleFor(d) }), el('span', { text: d.archived ? 'Archived · restore document' : new Date(d.updatedAt).toLocaleDateString(undefined, { month: 'short', day: 'numeric' }) })]); button.addEventListener('click', () => d.archived ? restoreDocument(d.id) : openDocument(d.id)); list.append(button); } $('archive-toggle').textContent = showArchived ? 'Show active' : 'Show archived'; }
let showingArchived = false;
function renderEditor({ preserveValue = false } = {}) { const d = active(); if (!d) return; $('document-title').value = d.title; $('direction-select').value = d.direction; $('font-select').value = d.font; const editor = $('editor'); if (!preserveValue) editor.value = d.text; editor.dir = d.direction === 'auto' ? 'auto' : d.direction; editor.classList.toggle('font-naskh', d.font === 'naskh'); editor.classList.toggle('font-nastaliq', d.font === 'nastaliq'); measure(); renderDocuments(showingArchived); }
function measure() { const text = active()?.text || ''; $('document-measure').textContent = `${scalarCount(text).toLocaleString()} scalars · ${bytes(text).toLocaleString()} bytes`; }
function openDocument(documentId, selection = null) { const doc = workspace.documents.find(d => d.id === documentId && !d.archived); if (!doc) return; workspace.activeId = documentId; history = []; renderEditor(); saveWorkspace(); go('write'); if (selection) requestAnimationFrame(() => { const editor = $('editor'); editor.focus(); editor.setSelectionRange(backingToDisplay(doc.text, selection.start), backingToDisplay(doc.text, selection.end)); savedSelection = selection; }); }
function archiveCurrent() { const d = active(); if (!d) return; if (!workspace.documents.some(other => other.id !== d.id && !other.archived)) { if (workspace.documents.length >= MAX_DOCS) return toast('Restore another document before archiving this one.'); workspace.documents.push(newDocument()); } d.archived = true; d.updatedAt = now(); workspace.activeId = workspace.documents.find(other => !other.archived).id; history = []; renderEditor(); saveWorkspace(); toast('Document archived. It remains recoverable here.'); }
function restoreDocument(documentId) { const d = workspace.documents.find(item => item.id === documentId); if (!d) return; d.archived = false; d.updatedAt = now(); workspace.activeId = d.id; showingArchived = false; history = []; renderEditor(); saveWorkspace(); toast('Document restored.'); }
function remember(text) { history.push(text); if (history.length > 30) history.shift(); }
function setDocumentText(next, { immediate = false, feedback = '' } = {}) { const d = active(); if (!d || next === d.text) return false; if (bytes(next) > MAX_BYTES) { $('editor').value = d.text; toast(`Text is limited to ${MAX_BYTES.toLocaleString()} UTF-8 bytes.`); return false; } remember(d.text); d.text = next; d.updatedAt = now(); $('editor').value = next; measure(); if (feedback) $('editor-feedback').textContent = feedback; if (immediate) saveWorkspace(); else saveSoon(); return true; }
function insertAtSelection(text) { if (currentRoute === 'word') { const input = $('word-query'); const start = wordSelection.start, end = wordSelection.end; const next = input.value.slice(0, start) + text + input.value.slice(end); input.value = next; const cursor = start + text.length; wordSelection = { start: cursor, end: cursor }; requestAnimationFrame(() => { input.focus(); input.setSelectionRange(cursor, cursor); }); clearTimeout(wordTimer); wordTimer = setTimeout(runWordSearch, 180); return; } const editor = $('editor'); const d = active(); if (!d) return; const start = Number.isInteger(savedSelection.start) ? savedSelection.start : displayToBacking(d.text, editor.selectionStart); const end = Number.isInteger(savedSelection.end) ? savedSelection.end : displayToBacking(d.text, editor.selectionEnd); const next = d.text.slice(0, start) + text + d.text.slice(end); if (setDocumentText(next, { feedback: 'Inserted' })) { const cursor = start + text.length; requestAnimationFrame(() => { editor.focus(); editor.setSelectionRange(backingToDisplay(next, cursor), backingToDisplay(next, cursor)); savedSelection = { start: cursor, end: cursor }; }); } }
function download(name, value, type = 'text/plain;charset=utf-8') { const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([value], { type })); a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(a.href), 1000); }
function setLabText(text) { labTextBacking = text; $('lab-text').value = text; latestPacket = null; currentParse = null; $('download-packet').disabled = true; }
function routeFromHash() { const route = location.hash.slice(1).split('?')[0]; return ['word','write','search','lab','learn'].includes(route) ? route : 'word'; }
function wordQueryFromHash() { const raw = location.hash.slice(1); const index = raw.indexOf('?'); if (index < 0) return ''; try { const query = new URLSearchParams(raw.slice(index + 1)).get('query') || ''; if (query.length > 500) { wordHashError = true; return ''; } wordHashError = false; return query; } catch { wordHashError = true; return ''; } }
function go(route, updateHash = true) { currentRoute = route; document.querySelectorAll('.view').forEach(v => v.classList.toggle('active', v.id === `${route}-view`)); document.querySelectorAll('[data-route]').forEach(b => b.classList.toggle('active', b.dataset.route === route)); if (updateHash && route !== routeFromHash()) location.hash = route; if (route === 'lab' && !labTextBacking) setLabText(active()?.text || ''); if (route === 'search') $('workspace-query').focus(); if (route === 'word') $('word-query').focus(); }
function updateWordHash(query) { const hash = query ? `#word?query=${encodeURIComponent(query)}` : '#word'; window.history.replaceState(null, '', hash); }
function sourceText(source) { return source ? `${source.title}${source.locator ? ` · ${source.locator}` : ''}` : ''; }
async function copyHeadword(value) { try { await navigator.clipboard.writeText(value); toast('Headword copied.'); } catch { toast('Copy is not available in this browser.'); } }
function wordDetail(label, value) { if (!value) return null; return el('p', { class: 'word-detail' }, [el('small', { text: label }), document.createTextNode(value)]); }
function languageLabel(value) { return value === 'en' ? 'English' : value === 'ur' ? 'Urdu' : 'Burushaski'; }
function renderWordResults(results, { browsing = false } = {}) { const root = $('word-results'); clear(root); if (!results.length) return; for (const result of results) { const entry = browsing ? result : result.entry; if (browsing) { const card = el('button', { type: 'button', class: 'word-browse' }, [el('strong', { text: entry.headword })]); for (const sense of entry.senses) card.append(el('span', { class: 'word-browse-sense' }, [el('small', { text: languageLabel(sense.language) }), document.createTextNode(sense.text)])); card.addEventListener('click', () => { $('word-query').value = entry.headword; wordSelection = { start: entry.headword.length, end: entry.headword.length }; runWordSearch(); }); root.append(card); continue; } const card = el('article', { class: 'word-entry' }); const heading = el('div', { class: 'word-heading' }, [el('h2', { text: entry.headword })]); const copy = el('button', { type: 'button', class: 'quiet-button', text: 'Copy' }); copy.addEventListener('click', () => copyHeadword(entry.headword)); heading.append(copy); card.append(heading); card.append(el('p', { class: 'word-match', text: `Matched ${result.match.kind} ${result.match.field}` })); const senses = el('div', { class: 'word-senses' }); for (const sense of entry.senses) senses.append(el('p', {}, [el('small', { text: languageLabel(sense.language) }), document.createTextNode(sense.text)])); card.append(senses); for (const example of entry.examples) { const exampleNode = el('div', { class: 'word-example' }, [el('p', { text: example.text })]); if (example.translation) exampleNode.append(el('p', { text: example.translation })); if (example.source) exampleNode.append(el('small', { text: sourceText(example.source) })); card.append(exampleNode); } card.append(wordDetail('Dialect', entry.dialect)); card.append(wordDetail('Source', sourceText(entry.source))); if (entry.roman) card.append(wordDetail('Source-recorded Roman spelling', `${entry.roman.text} · ${sourceText(entry.roman.source)}`)); if (entry.pronunciation) card.append(wordDetail(`Source-recorded pronunciation (${entry.pronunciation.notation})`, `${entry.pronunciation.text}${entry.pronunciation.source ? ` · ${sourceText(entry.pronunciation.source)}` : ''}`)); else card.append(wordDetail('Pronunciation', 'Pronunciation not supplied by this source.')); root.append(card); } }
function showWordBrowse() { const root = $('word-results'); clear(root); if (!wordCollection) return; $('word-summary').textContent = `${wordCollectionLabel}Choose an available headword, or enter a search.`; renderWordResults(wordCollection.entries, { browsing: true }); }
async function runWordSearch() { const query = $('word-query').value; clearTimeout(wordTimer); if (!wordCollection) return; updateWordHash(query); if (!query) return showWordBrowse(); $('word-summary').textContent = 'Searching source-attributed records…'; clear($('word-results')); try { const answer = await searchWords(wordCollection, query, { limit: 50 }); $('word-summary').textContent = wordCollectionLabel + (answer.total ? (answer.truncated ? 'Showing the available returned records.' : 'Source-attributed records returned.') : 'No source-attributed record was returned for this search.'); renderWordResults(answer.results || []); } catch (error) { $('word-summary').textContent = `Word search could not run: ${error.message}`; } }
async function loadWordCollection() { try { const response = await fetch('./word-data.json'); if (!response.ok) throw new Error('The local word data could not be loaded.'); wordCollection = validateCollection(await response.json()); wordCollectionLabel = wordCollection.publicationStatus === 'review' ? 'Preview collection. ' : ''; const initialQuery = wordQueryFromHash(); $('word-query').value = initialQuery; if (wordHashError) { $('word-summary').textContent = 'The linked word query is too long.'; clear($('word-results')); } else if (initialQuery) await runWordSearch(); else showWordBrowse(); } catch (error) { $('word-summary').textContent = `Word lookup is unavailable: ${error.message}`; clear($('word-results')); } }

function findNext() { const query = $('find-input').value; const text = active()?.text || ''; if (!query) return $('find-status').textContent = 'Enter text to find.'; const editor = $('editor'); const match = Engine.findNext(text, query, displayToBacking(text, editor.selectionEnd), { matchCase: true }); if (!match) return $('find-status').textContent = 'No match.'; editor.focus(); editor.setSelectionRange(backingToDisplay(text, match.start), backingToDisplay(text, match.end)); savedSelection = { start: match.start, end: match.end }; $('find-status').textContent = `${match.start + 1}–${match.end}${match.wrapped ? ' · returned to start' : ''}`; }
function replaceOne() { const query = $('find-input').value; const replacement = $('replace-input').value; const editor = $('editor'); const d = active(); if (!query || !d) return; const start = displayToBacking(d.text, editor.selectionStart), end = displayToBacking(d.text, editor.selectionEnd); if (d.text.slice(start, end) !== query) { findNext(); return; } const next = Engine.replaceRange(d.text, { start, end }, replacement); if (setDocumentText(next, { immediate: true, feedback: 'Replaced 1 match' })) { const cursor = start + replacement.length; editor.focus(); editor.setSelectionRange(backingToDisplay(next, cursor), backingToDisplay(next, cursor)); savedSelection = { start: cursor, end: cursor }; findNext(); } }
function replaceEvery() { const d = active(), query = $('find-input').value, replacement = $('replace-input').value; if (!d || !query) return; const result = Engine.replaceAll(d.text, query, replacement, { matchCase: true }); const next = result.text; const count = result.count; if (setDocumentText(next, { immediate: true, feedback: `Replaced ${count} ${count === 1 ? 'match' : 'matches'}` })) $('find-status').textContent = `Replaced ${count} ${count === 1 ? 'match' : 'matches'}.`; }
function undo() { const previous = history.pop(); if (previous === undefined) return toast('Nothing to undo.'); const d = active(); d.text = previous; d.updatedAt = now(); $('editor').value = previous; measure(); saveWorkspace(); $('editor-feedback').textContent = 'Undid last change'; }

function displayKeyboard() { const holder = $('key-rows'); clear(holder); const layer = Number($('keyboard-layer').value); const extra = Object.keys(keyboard?.keys || {}).filter(code => !keyboardRows.flat().includes(code)); for (const row of [...keyboardRows, extra]) { if (!row.length) continue; const rowEl = el('div', { class: 'key-row' }); for (const code of row) { const variants = keyboard?.keys?.[code] || []; const entry = variants[layer]; const char = entry?.char || ''; const label = entry?.codepoints?.join(' ') || 'Not mapped'; const shown = /\p{M}/u.test(char) ? `◌${char}` : char; const btn = el('button', { type: 'button', class: 'key', title: `${code}: ${label}`, 'aria-label': char ? `${code}, ${label}` : `${code}, not mapped`, disabled: char ? null : true }, [el('span', { class: 'character', text: shown }), el('span', { class: 'hardware', text: code.replace('Key','').replace('Digit','') })]); if (char) btn.addEventListener('click', () => insertAtSelection(char)); rowEl.append(btn); } holder.append(rowEl); } const specials = $('special-letters'); clear(specials); for (const item of specialLetters) { const button = el('button', { type: 'button', title: item.codepoints.join(' '), text: item.char, 'aria-label': item.codepoints.join(' ') }); button.addEventListener('click', () => insertAtSelection(item.char)); specials.append(button); } }
function toggleKeyboard(force) { const drawer = $('keyboard-drawer'); const open = force ?? !drawer.classList.contains('open'); if (open && currentRoute !== 'word') go('write'); drawer.classList.toggle('open', open); drawer.inert = !open; document.body.classList.toggle('keyboard-open', open); drawer.setAttribute('aria-hidden', String(!open)); $('keyboard-toggle').setAttribute('aria-expanded', String(open)); if (open) displayKeyboard(); }
function handleHardware(event) { if (!$('hardware-toggle').checked || !$('keyboard-drawer').classList.contains('open') || event.isComposing || event.ctrlKey || event.metaKey || event.altKey && !event.getModifierState('AltGraph')) return; const layer = event.getModifierState('AltGraph') ? (event.shiftKey ? 3 : 2) : (event.shiftKey ? 1 : 0); const entry = keyboard?.keys?.[event.code]?.[layer]; if (!entry?.char) return; event.preventDefault(); insertAtSelection(entry.char); }

function renderSearch(results) { const holder = $('search-results'); clear(holder); if (!results.length) return; for (const result of results) { const b = el('button', { type: 'button', class: 'result-card' }); b.append(el('h3', { text: `${result.title || 'Untitled document'} · line ${result.line}` })); const p = el('p'); p.append(document.createTextNode(result.before)); p.append(el('mark', { text: result.match })); p.append(document.createTextNode(result.after)); b.append(p); b.addEventListener('click', () => openDocument(result.documentId, { start: result.start, end: result.end })); holder.append(b); } }
async function runSearch() { const query = $('workspace-query').value; const holder = $('search-results'); clear(holder); searchState = []; if (!query) return $('search-summary').textContent = 'Enter text to search your documents.'; const docs = workspace.documents.filter(d => !d.archived).map(({id,title,text}) => ({id,title,text})); const result = Engine.searchDocuments ? Engine.searchDocuments(docs, query, { limit: Engine.MAX_RESULTS || 200 }) : { matches: [], total: 0, truncated: false }; const answer = await result; searchState = answer.matches || []; $('search-summary').textContent = answer.total ? `${answer.total}${answer.truncated ? '+' : ''} exact ${answer.total === 1 ? 'match' : 'matches'} in local documents.` : 'No exact matches in active local documents.'; $('download-results').disabled = !searchState.length; renderSearch(searchState); }
function resultsTSV() { const esc = (value) => { let s = String(value).replace(/[\t\r\n]/g, ' '); return /^[\s\ufeff]*[=+\-@]/.test(s) ? `'${s}` : s; }; return ['document\tline\tbefore\tmatch\tafter', ...searchState.map(r => [r.title,r.line,r.before,r.match,r.after].map(esc).join('\t'))].join('\n'); }

function metrics(parsed) { const grid = el('div', { class: 'metric-grid' }); for (const [label, value] of [['Format',parsed.format || 'Text'],['Bytes',String(parsed.byteLength)],['Scalars',String(parsed.scalarCount)],['SHA-256',parsed.sha256 || 'Unavailable']]) grid.append(el('div', { class: 'metric' }, [el('small',{text:label}),el('strong',{text:value})])); return grid; }
function renderStructure(parsed) { const root = $('lab-result'); clear(root); root.append(metrics(parsed)); root.append(el('h3', { text: 'Runs' })); const list = el('div'); for (const run of (parsed.runs || []).slice(0, 120)) list.append(el('p', { text: `${run.kind}: ${run.start}–${run.end}  ${run.text}` })); if ((parsed.runs || []).length > 120) list.append(el('p', { text: `Showing the first 120 of ${parsed.runs.length} runs.` })); root.append(list); }
function renderUnicode(parsed) { const root = $('lab-result'); clear(root); root.append(metrics(parsed)); const table = el('table', { class: 'scalar-table' }); table.append(el('thead', {}, [el('tr', {}, ['#','Character','Code point','UTF-16','Byte','Kind'].map(x => el('th',{text:x})))])); const body = el('tbody'); for (const s of (parsed.scalars || []).slice(0, 300)) body.append(el('tr', {}, [s.index,s.char === ' ' ? '␠' : s.char,s.codePoint,s.utf16Offset,s.byteOffset,s.kind].map(x => el('td',{text:String(x)})))); table.append(body); root.append(table); if ((parsed.scalars || []).length > 300) root.append(el('p',{text:`Showing the first 300 of ${parsed.scalars.length} scalars.`})); }
function renderCompare() { const root = $('lab-result'); clear(root); const controls = el('div', { class: 'compare-controls' }); const original = el('textarea', { 'aria-label': 'Original text for comparison', placeholder: 'Original text' }); original.value = active()?.originalText || ''; const revised = el('textarea', { 'aria-label': 'Revision text for comparison', placeholder: 'Revision text' }); revised.value = $('lab-text').value; const button = el('button',{type:'button',text:'Compare versions'}); const output = el('div'); button.addEventListener('click', async () => { clear(output); output.textContent = 'Comparing versions…'; try { const diff = await Engine.compareTexts(original.value, revised.value); clear(output); output.append(el('p',{text:diff.equal ? 'The two versions are identical.' : `Difference strategy: ${diff.strategy || 'text comparison'}.`})); const line = el('div',{class:'difference'}); for (const change of diff.changes || []) { const tag = change.type === 'insert' ? 'ins' : change.type === 'delete' ? 'del' : 'span'; line.append(el(tag,{text:change.text})); } output.append(line); } catch (error) { output.textContent = `Could not compare these texts: ${error.message}`; } }); controls.append(original,revised,button,output); root.append(controls); }
function renderLab() { if (!currentParse) return; if (labTab === 'structure') renderStructure(currentParse); else if (labTab === 'unicode') renderUnicode(currentParse); else renderCompare(); }
async function parseLab() { const text = labTextBacking; if (bytes(text) > MAX_BYTES) return toast(`Text is limited to ${MAX_BYTES.toLocaleString()} UTF-8 bytes.`); $('lab-result').textContent = 'Parsing text…'; latestPacket = null; $('download-packet').disabled = true; try { currentParse = await Engine.parseText(text); latestPacket = currentParse; $('download-packet').disabled = false; renderLab(); } catch (error) { currentParse = null; $('lab-result').textContent = `Could not parse this text: ${error.message}`; } }

function renderGuides() { const root = $('learn-guides'); for (const guide of guides) { const card = el('article',{class:'guide'},[el('h2',{text:guide.title}),el('p',{text:guide.text})]); const button = el('button',{type:'button',text:guide.action}); button.addEventListener('click',() => go(guide.route)); card.append(button); root.append(card); } }
function nextPractice() { if (!practiceChars.length) return; practiceIndex = (practiceIndex + 1) % practiceChars.length; $('practice-prompt').textContent = practiceChars[practiceIndex]; $('practice-input').value = ''; $('practice-feedback').textContent = ''; }

async function importText(file) { if (!file) return; if (file.size > MAX_BYTES) return toast(`This file is larger than ${MAX_BYTES.toLocaleString()} bytes.`); try { const value = Engine.decodeUtf8 ? Engine.decodeUtf8(new Uint8Array(await file.arrayBuffer())) : await file.text(); const doc = newDocument(file.name.replace(/\.(txt|md)$/i,''), value); if (workspace.documents.length >= MAX_DOCS) return toast(`The workspace can hold up to ${MAX_DOCS} documents.`); workspace.documents.push(doc); workspace.activeId = doc.id; history = []; renderEditor(); saveWorkspace(); toast('Text opened as a local document.'); } catch (error) { toast(`Could not open this text file: ${error.message}`); } }
async function importWorkspace(file) { if (!file) return; if (file.size > MAX_BYTES * 30) return toast('This workspace file is too large to import.'); try { const raw = new Uint8Array(await file.arrayBuffer()); const text = new TextDecoder('utf-8', { fatal: true, ignoreBOM: true }).decode(raw); const incoming = validateWorkspace(JSON.parse(text)); const room = MAX_DOCS - workspace.documents.length; if (incoming.documents.length > room) throw new Error(`This workspace has ${incoming.documents.length} documents, but only ${room} local document slots remain.`); const existing = new Set(workspace.documents.map(d => d.id)); const received = incoming.documents.map(d => { const copy = { ...d }; if (existing.has(copy.id)) copy.id = id(); existing.add(copy.id); return copy; }); workspace.documents.push(...received); workspace.activeId = received.find(d => !d.archived)?.id || workspace.activeId; history = []; renderEditor(); saveWorkspace(); toast(`${received.length} document${received.length === 1 ? '' : 's'} added to this workspace.`); } catch (error) { toast(`Could not import workspace: ${error.message}`); } finally { $('import-workspace').value = ''; } }
async function openPacket(file) { if (!file) return; try { const value = JSON.parse(await file.text()); const text = await Engine.reconstructPacket(value); setLabText(text); await parseLab(); toast('Packet reconstructed.'); } catch (error) { toast(`Could not open packet: ${error.message}`); } }

function bind() {
  document.querySelectorAll('[data-route]').forEach(button => button.addEventListener('click',() => { go(button.dataset.route); if (window.matchMedia('(max-width: 760px)').matches) setSidebarOpen(false); }));
  $('new-document').addEventListener('click',() => { if (workspace.documents.length >= MAX_DOCS) return toast(`The workspace can hold up to ${MAX_DOCS} documents.`); const d = newDocument(); workspace.documents.push(d); workspace.activeId = d.id; history = []; renderEditor(); saveWorkspace(); $('editor').focus(); });
  $('archive-toggle').addEventListener('click',() => { showingArchived = !showingArchived; renderDocuments(showingArchived); }); $('archive-document').addEventListener('click',archiveCurrent);
  $('document-title').addEventListener('input',(e) => { const d=active(); d.title=e.target.value; d.updatedAt=now(); renderDocuments(showingArchived); saveSoon(); });
  $('document-title').addEventListener('change',() => saveWorkspace());
  $('direction-select').addEventListener('change',(e) => { active().direction=e.target.value; renderEditor({preserveValue:true}); saveWorkspace(); });
  $('font-select').addEventListener('change',(e) => { active().font=e.target.value; renderEditor({preserveValue:true}); saveWorkspace(); });
  $('editor').addEventListener('input',(e) => setDocumentText(e.target.value));
  const rememberSelection = (target) => { const text = active()?.text || ''; savedSelection={start:displayToBacking(text,target.selectionStart),end:displayToBacking(text,target.selectionEnd)}; };
  $('editor').addEventListener('select',e => rememberSelection(e.target));
  $('editor').addEventListener('keyup',e => rememberSelection(e.target));
  $('editor').addEventListener('click',e => rememberSelection(e.target));
  $('editor').addEventListener('keydown',handleHardware);
  document.addEventListener('keydown',(e) => { if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === 's') { e.preventDefault(); const d=active(); download(`${safeName(titleFor(d))}.txt`,d.text); toast('Text downloaded.'); } });
  $('find-next').addEventListener('click',findNext); $('replace-one').addEventListener('click',replaceOne); $('replace-all').addEventListener('click',replaceEvery); $('undo-edit').addEventListener('click',undo);
  $('open-text').addEventListener('change',e => importText(e.target.files[0])); $('import-workspace').addEventListener('change',e => importWorkspace(e.target.files[0]));
  $('export-text').addEventListener('click',() => { const d=active(); download(`${safeName(titleFor(d))}.txt`,d.text); }); $('export-workspace').addEventListener('click',() => download('alyas-nasiri-workspace.json',JSON.stringify(workspace,null,2),'application/json'));
  $('download-recovery').addEventListener('click',()=> { const bundle = readRecoveryBundle(); if (corruptWorkspaceBackup) bundle.recoveries.push({ capturedAt: now(), reason: 'unreadable local workspace', data: corruptWorkspaceBackup }); if (bundle.recoveries.length) download('alyas-nasiri-workspace-recovery.json',JSON.stringify(bundle,null,2),'application/json'); else toast('No recovery copy is available.'); });
  $('keyboard-toggle').addEventListener('click',()=>toggleKeyboard()); $('keyboard-close').addEventListener('click',()=>toggleKeyboard(false)); $('keyboard-layer').addEventListener('change',displayKeyboard); $('keyboard-drawer').addEventListener('click',(e)=>{ const action=e.target.dataset.keyAction; if(action==='space') insertAtSelection(' '); if(action==='enter') insertAtSelection('\n'); if(action==='backspace'){ if(currentRoute==='word'){ const input=$('word-query'),start=wordSelection.start,end=wordSelection.end; const deletion=end>start?{text:input.value.slice(0,start)+input.value.slice(end),cursor:start}:Engine.deletePreviousGrapheme(input.value,start); const cursor=deletion.cursor; input.value=deletion.text;wordSelection={start:cursor,end:cursor};input.focus();input.setSelectionRange(cursor,cursor);clearTimeout(wordTimer);wordTimer=setTimeout(runWordSearch,180);return; } const d=active(), start=savedSelection.start,end=savedSelection.end; const next=end>start ? { text:d.text.slice(0,start)+d.text.slice(end), cursor:start } : Engine.deletePreviousGrapheme(d.text,start); if(setDocumentText(next.text,{feedback:'Deleted'})){ $('editor').focus(); const shown=backingToDisplay(next.text,next.cursor); $('editor').setSelectionRange(shown,shown); savedSelection={start:next.cursor,end:next.cursor}; } }});
  $('word-search').addEventListener('click',runWordSearch); $('word-query').addEventListener('input', e => { wordSelection={start:e.target.selectionStart,end:e.target.selectionEnd}; clearTimeout(wordTimer); wordTimer=setTimeout(runWordSearch,180); }); ['select','keyup','click'].forEach(type => $('word-query').addEventListener(type,e=>wordSelection={start:e.target.selectionStart,end:e.target.selectionEnd})); $('word-query').addEventListener('keydown',handleHardware); $('word-query').addEventListener('keydown',e => { if(e.key==='Enter'){e.preventDefault();runWordSearch();} }); $('workspace-search').addEventListener('click',runSearch); $('workspace-query').addEventListener('keydown',e => { if(e.key==='Enter') runSearch(); }); $('download-results').addEventListener('click',()=>{ download('alyas-nasiri-search-results.tsv',resultsTSV(),'text/tab-separated-values;charset=utf-8'); });
  $('use-current').addEventListener('click',()=> setLabText(active()?.text||'')); $('lab-text').addEventListener('input', e => { labTextBacking=e.target.value; latestPacket=null; currentParse=null; $('download-packet').disabled=true; }); $('parse-text').addEventListener('click',parseLab); $('download-packet').addEventListener('click',()=> download('alyas-nasiri-text-packet.json',JSON.stringify(latestPacket,null,2),'application/json')); $('open-packet').addEventListener('change',e=>openPacket(e.target.files[0]));
  document.querySelectorAll('[data-lab-tab]').forEach(b=>b.addEventListener('click',()=>{labTab=b.dataset.labTab;document.querySelectorAll('[data-lab-tab]').forEach(x=>x.setAttribute('aria-selected',String(x===b)));if(currentParse)renderLab();}));
  $('practice-input').addEventListener('input',e=>{ const expected=$('practice-prompt').textContent; if(e.target.value===expected){$('practice-feedback').textContent='Matched.';setTimeout(nextPractice,450);} else if(e.target.value){$('practice-feedback').textContent='Try the displayed character.';} });
  document.querySelector('.menu-toggle')?.addEventListener('click',()=>setSidebarOpen(!$('document-sidebar').classList.contains('open')));
}
function setSidebarOpen(open) { const sidebar = $('document-sidebar'); const mobile = window.matchMedia('(max-width: 760px)').matches; sidebar.classList.toggle('open',open); sidebar.inert = mobile && !open; sidebar.setAttribute('aria-hidden',String(mobile && !open)); document.querySelector('.menu-toggle').setAttribute('aria-expanded',String(open)); }
async function start() { loadWorkspace(); try { keyboard = await (await fetch('./keyboard.json')).json(); const specials = await (await fetch('./special-letters.json')).json(); specialLetters = specials.special_letters || []; } catch { keyboard = { keys: {} }; toast('Keyboard data could not load.'); } practiceChars = Object.values(keyboard.keys).flatMap(values => values.map(v=>v?.char).filter(Boolean)).filter((v,i,a)=>a.indexOf(v)===i); renderGuides(); bind(); renderEditor(); displayKeyboard(); nextPractice(); setSidebarOpen(false); $('keyboard-drawer').inert = true; go(routeFromHash(),false); await loadWordCollection(); if (corruptWorkspaceBackup || hasRecovery()) { $('download-recovery').hidden = false; if (corruptWorkspaceBackup) toast('A previous local workspace could not be read. Download its recovery copy before continuing.'); } else if (!saveWorkspace()) setSave('Not yet saved locally'); window.addEventListener('pagehide',flushSave); document.addEventListener('visibilitychange',()=>{ if(document.visibilityState==='hidden') flushSave(); }); window.addEventListener('hashchange',()=>{ const route=routeFromHash(); go(route,false); if(route==='word'){ const query=wordQueryFromHash(); $('word-query').value=query; runWordSearch(); } }); window.addEventListener('storage',(event)=>{ if(event.key===STORAGE_KEY && event.newValue){ const retained=retainRecovery(event.newValue,'workspace changed in another tab'); externalConflictHold=true; $('download-recovery').hidden=false; setSave(retained ? 'Changed in another tab; recovery copy kept' : 'Changed in another tab; save paused'); toast(retained ? 'Another tab changed the local workspace. This tab remains open.' : 'Another tab changed the workspace. Save is paused; export this tab first.'); } }); if ('serviceWorker' in navigator && !['localhost', '127.0.0.1'].includes(location.hostname)) navigator.serviceWorker.register('/sw.js').catch(() => {}); }
window.addEventListener('hashchange', () => { if (routeFromHash() === 'word') { wordQueryFromHash(); if (wordHashError) setTimeout(() => { $('word-summary').textContent = 'The linked word query is too long.'; clear($('word-results')); }, 0); } });
start();
